version: "3"

services:
  recipe-app-api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src/RecipeAppAPI:/RecipeAppAPI
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=postgres_db
      - DB_NAME=recipe-app-api_data
      - DB_USER=postgres
      - DB_PASS=publicPassword

  postgres_db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=recipe-app-api_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=publicPassword
